### ISSUE TITLE
Why do you live in Ohio? Why not the Valley?

### ISSUE THREAD

**Issue by benstr** [queso/ama#2]
![Silicon](http://www.spidersweb.pl/wp-content/uploads/2014/05/tumblr_n3h5yaPY6o1trb5guo1_1280.jpg)

**Comment by queso** [comment]
Great picture! 

Let me just say up front that I really enjoy my life and the way it is setup with my wife and kids. That being said, I blame my parents for moving from San Jose to Cincinnati when I was 5 years old. So I've grown up in Cincinnati most of my life despite being born in California.

The reason I am staying here is a much deeper question. I got married when I was 21 and had my first child when I was 25. Unforunately things didn't work out with my x-wife and we parted ways, but we share equal custody of our son and I prefer to keep it that way. I think it is important to have a connection with your biological parents. My biological parents split when I was 1 year old and I never really got the chance to connect much with my biological father because he stayed in California. I just think there are certain deeper connections that happen when you have shared DNA with someone, like they get why you are a certain way. So sticking around Ohio is important for me while I raise my son :)
