### ISSUE TITLE
Are the Meteor alternatives tempting you...

### ISSUE THREAD

**Issue by tomRedox** [queso/ama#3]
It seems like the chatter around new frameworks is getting louder?

**Comment by queso** [comment]
It might help if you explain what you mean by alternatives... Do you mean more like Mantra or something like Feathers.js?

**Comment by tomRedox** [comment]
I was thinking more around Feathers or home-rolled alternatives.  It feels like React makes those types of alternatives seem less of a jump than they did with a Blaze front-end/

**Comment by queso** [comment]
I'll be honest here, the use of React.js certainly has me questions things. I am already starting to push out beyond the borders of the Meteor package system and trying to rely directly on npm based React packages to get front-end functionality with React. Like using React-Helmet instead of DocHead from Kadira. I will likely switch over to ReactRouter at some point, when I get more time to play with SSR.

The thing with Meteor (as it stands at the moment) is that it still requires a lot of buy-in even with their React/Angular support. Things like fibers hold back the ability to upgrade to a more current version of Node, for example. I also feel pretty uncertain for the future of DDP now that Apollo is a major focus for MDG.

That is a long winder way for me to say, Yes, I am paying attention to the chatter around new frameworks because they are much more modern than Meteor (Express, ORMs for data sources, REST support, newer Node versions, etc)

**Comment by JamesReece** [comment]
Does Restivus package offer the same level of REST support in Meteor?  

I've spent a day reading around Feathersjs and following the slack chat. As a Meteor dev still on stabilisers (training wheels to US), as much as I like the SOA + [hooks / AOP] approach there are still so many choices left to me that I am scared to have.  Meteor takes care of so many things I don't yet understand.

I'd love to make the most of a minimalist framework but it requires a deeper knowledge, right?
