### ISSUE TITLE
SOA and REST in Meteor

### ISSUE THREAD

**Issue by JamesReece** [queso/ama#7]
Reading around Feathersjs and following the slack chat... as a Meteor dev still on training wheels, Feathersjs leaves so many choices to me that I am scared to have. I'd love to make the most of a minimalist framework but feel it requires a deeper knowledge.

What I do love is the SOA + REST API + [hooks / AOP] approach.

Don't you think Apollo / v1.3 will bring a lot of this to Meteor?  Do you / have you structured a meteor project in a SOA way? Know any tutorials in that?

**Comment by JamesReece** [comment]
Things move fast.. Meteor 1.3 released today and you've just done a podcast on feathersjs - I'll go and watch that.  Closing my question.

**Comment by queso** [comment]
My problem with Meteor is that they aren't really setup well to support any type of SOA. Feathers is in a much smarter position to deal with it because they are using JWT to handle authentication. Sadly, Meteor has no built in way to handle authentication way to handle services, you would have to build it yourself.

If SOA is interesting, I would take a serious look at Feathers.
